name: Renin_Cells_with_Diff_Conditions

pep_version: 2.0.0
sample_table: renin_annotation.csv

looper:  # relative paths are relative to this config file
  output_dir: $PROCESSED/gomez_atac/results_pipeline/variable/ 
  pipeline_interfaces: $CODE/pepatac/project_pipeline_interface.yaml  # PATH to the directory where looper will find the pipeline repository. 

sample_modifiers:
  append:
    pipeline_interfaces: $CODE/pepatac/sample_pipeline_interface.yaml
  imply:
    - if: 
        organism: ["mouse", "Mus Musculus", "Mouse"]
      then: 
        genome: mm10
        macs_genome_size: mm
        prealignments: mouse_chrM2x
        aligner: bowtie2         # Default. [options: bwa]
        deduplicator: samblaster # Default. [options: picard]
        trimmer: skewer          # Default. [options: pyadapt, trimmomatic]
        peak_type: variable         # Default. [options: variable]
        extend: "250"            # Default. For fixed-width peaks, extend this distance up- and down-stream.
        frip_ref_peaks: None     # Default. Use an external reference set of peaks instead of the peaks called from this run


