name: susztak_DNase

pep_version: 2.0.0
sample_table: susztak_annotation.csv

looper:  # relative paths are relative to this config file
  output_dir: $PROCESSED/gomez_atac/results_pipeline/susztak
  pipeline_interfaces: $CODE/pepatac/project_pipeline_interface.yaml  # PATH to the directory where looper will find the pipeline repository.

sample_modifiers:
  append:
    pipeline_interfaces: $CODE/pepatac/sample_pipeline_interface.yaml
  derive:
    attributes: [read1, read2]
    sources:
      R1: "$DATA/gomez_atac/Susztak/fastq/{file_accession_1}.fastq.gz"
      R2: "$DATA/gomez_atac/Susztak/fastq/{file_accession_2}.fastq.gz"
  imply:
    - if: 
        organism: ["mouse", "Mus Musculus", "Mouse", "Mus musculus"]
      then: 
        genome: mm10
        genome_size: mm
        prealignment_names: ["mouse_chrM2x"]
        aligner: bowtie2         # Default. [options: bwa]
        deduplicator: samblaster # Default. [options: picard]
        trimmer: skewer          # Default. [options: pyadapt, trimmomatic]
        peak_type: variable         # Default. [options: variable]
        extend: "250"            # Default. For fixed-width peaks, extend this distance up- and down-stream.
        frip_ref_peaks: None     # Default. Use an external reference set of peaks instead of the peaks called from this run
